---
title: "Homework 4"
subtitle: "BIOST 311"
author: "Nina Galanter"
date: \today
output: 
  pdf_document:
    toc: false
header-includes:
  - \usepackage{color}
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(formatR)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = "hide")
```


## Instructions

This assignment should be submitted on Canvas as a .pdf by 11:59pm on Thursday, April 27th. You are welcome to work together on the homework; however, final solutions should be written up individually. 

Unedited software output in the body of your assignment is not acceptable. Please round numerical values to 2--3 significant digits, and include your R code (if applicable) in the same document. See the "How to Write a Proper Homework" document on Canvas for additional guidelines.  

Each homework assignment is worth 20 points total. Problems are graded for correctness, according to the number of points given in the problem statement. Homeworks will be marked complete if you get at least 16/20 points, otherwise the homework is incomplete pending a possible revision. 

## 1. Confounding, Precision variables, and Causal Pathways

For the entirety of this question, suppose we are interested in the association between First Steps participation and birth weight (in grams). Recall that this was the original question our dataset was collected to try to answer! As a reminder, First Steps provided free pre-natal care to low income, pregnant individuals.

In particular, we are interested in whether or not First Steps participation *causes* higher birth weights, though we know that we cannot confidently make causal statements in an observational study. Nevertheless, it may still be useful to control for potential confounders in our study to get *as close as possible* to being able to make causal statements (remember that if we are able to adjust for *all* possible confounding variables in an observational study, we can make causal statements).

**For these next 3 questions, there is not necessarily a right answer. You are not expected to do any research - just support your answers using your own intuition or background knowledge.**

a. Suppose we are interested in including `education` as an additional variable in our model. What role do you think education plays in the relationship between First Steps and birth weight (confounder, precision variable, or neither)? Explain your reasoning. (2 points)

b. Suppose we are interested in including `wpre` as an additional variable in our model. What role do you think pre pregnancy weight plays in the relationship between First Steps and birth weight (confounder, precision variable, or neither)? Explain your reasoning. (2 points)

c. Identify a variable in the `births` dataset that could be on the causal pathway between First Steps participation and birth weight. Explain your reasoning. (2 points)

## 2. Effect modification

For this question, we will explore effect modification in the `births` dataset.  
**Note: I am not expecting you to provide any confidence intervals that aren't included in the output of `confint()`**

a. Load the `births` dataset (0 points)

b. Create a graph visualizing the relationship between `bwt` and `age`, and include information on `drink` however you see fit. Use jittered points. Add two linear regression lines to your plot: one for the relationship between `bwt` and `age` among those who did not drink, and one for the relationship between `bwt` and `age` among those who did drink. Use labels to make clear what each part of your plot represents. **Hint: look into geom_smooth() for the regression lines** (2 pts)

c. Perform a multiple linear regression analysis to assess whether and how drinking modifies the relationship between parental age (predictor of interest) and birth weight (outcome). (2 pts)
**Just perform the analysis for this question**

d. State and interpret the estimate of the association between parental age and birth weight among birth parents who **did not** drink during pregnancy. (2 pts)

e. State and interpret the estimate of the association between parental age and birth weight among birth parents who **did** drink during pregnancy. (2 pts)

f. State and interpret the estimate of the interaction term coefficient. (1 pts)

g. Use the results from part c to perform a hypothesis test of whether drinking modifies the relationship between parental age and birth weight. Make sure to state your null and alternative hypotheses. (2 pts)


h. Evaluate the four classical linear regression assumptions for the model you fit in part (c). Include plots as necessary, and discuss whether or not you believe each assumption is met. (3 pts)
