---
title: "Homework 6"
subtitle: "BIOST 311"
author: "Nina Galanter"
date: \today
output: 
  pdf_document:
    toc: false
header-includes:
  - \usepackage{color}
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(formatR)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = "hide")
```


## Instructions

This assignment should be submitted on Canvas as a .pdf by 11:59pm on Thursday, May 11th. You are welcome to work together on the homework; however, final solutions should be written up individually. 

Unedited software output in the body of your assignment is not acceptable. Please round numerical values to 2--3 significant digits, and include your R code (if applicable) in the same document. See the "How to Write a Proper Homework" document on Canvas for additional guidelines.  

Each homework assignment is worth 20 points total. Problems are graded for correctness, according to the number of points given in the problem statement. Homeworks will be marked complete if you get at least 16/20 points, otherwise the homework is incomplete pending a possible revision. 


## 3. Simple logistic regression with a binary variable

We will use the `births` dataset and again study if First Steps participation (exposure) is associated with preterm births (outcome), defined as gestation time less than 37 weeks. 

a. Translate the scientific question above into a statistical question that can be answered using simple *logistic* regression. (2 point)

b. Create a preterm variable and perform a logistic regression analysis to answer the statistical question from part (a). Be sure to include a statistic with appropriate uncertainty quantification, as well as a hypothesis test. Be sure to state the null and alternative hypotheses. You should interpret your results; don’t just give numerical output. (3 points)

c. Compare your estimate from part (b) to the odds ratio you (or the solution key) estimated in Homework 5 Question 2 part (h). What do you notice? (2 point)

## 3. Simple logistic regression with a continuous variable

Now we will study if age of the birth parent (exposure) is associated with preterm births (outcome), defined as gestation time less than 37 weeks. 

a. Translate the scientific question above into a statistical question that can be answered using simple *logistic* regression. (2 point)

b. Perform a logistic regression analysis to answer the statistical question from part (a). Be sure to include a statistic with appropriate uncertainty quantification, as well as a hypothesis test. Be sure to state the null and alternative hypotheses. You should interpret your results; don’t just give numerical output. (3 points)


## 2. Multiple logistic regression

In this question, we will continue to study the association between first step participation and preterm births.

a. We might believe that age has a causal effect on both the probability of participating in first steps and the probability of a preterm birth. To account for this, fit a multiple logistic regression model with preterm birth as the outcome, first steps participation as the predictor of interest, and age as an adjustment variable. State the estimate that answers the question of interest with appropriate uncertainty quantification, as well as a hypothesis test. Be sure to state the null and alternative hypotheses. You should interpret your results; don’t just give numerical output. (3 points)

b. Perform a multiple logistic regression to investigate whether or not age acts as an effect modifier for the association between first steps participation and preterm births, and perform a hypothesis test for effect modification. Be sure to state your null and alternative hypotheses and interpret your results. (2 points)


c. Using your model from part (b), estimate the association between first steps participation and preterm births for subjects who are 25 years old and for subjects who are 35 years old (using only your logistic regression model). (3 points)




