---
title: 'Data Analysis Project, Peer Review'
subtitle: "BIOST 311: Regression Methods in the Health Sciences"
author: "Nina Galanter"
date: "Spring Quarter 2023; Submit on Canvas by 26 May 2023"
output: pdf_document
fontsize: 12pt
---

# Instructions

Peer review is a critical step in the process of scientific research. Whether written research is published in a formal academic journal or casually disseminated among colleagues, it almost always goes through some version of peer review. This allows fellow researchers with relevant expertise to assess the soundness, clarity, and overall quality of the methodology, interpretation, and communication. 

For this assignment, I am asking you to review a classmate's data analysis project first draft. Your goal is to provide useful feedback on both major and minor points, in order for the author to improve their project in the final report. You will structure your peer review as a formal peer review for a scientific journal (more details below). This will allow you to get a feel for how research dissemination works!

This assignment is limited to **two pages**, and your written text should use at least 12-point font. See the guidelines below for a list of components that need to be included. You should submit your assignment as a pdf file *without your name attached* so that your comments remain anonymous.

Submit your *Peer Review* on Canvas by 11:59pm on May 26. **Do not discuss your peer review with other students or post questions about your project on the Canvas discussion board.** But, feel free to ask me any questions in person/via Canvas instead!
 
This assignment is is graded on effort/completion. 

# Rubric:

## Formatting (1 point)

To receive full credit for the assignment, you should...

- use 12 point font
- write no more than two pages
- write in full sentences

## Overall assessment 

**Provide a brief summary of what the aims of the project are, as well as the main findings and implications. What were the primary methods used to answer the scientific questions? What are the contributions of this project to our understanding of the primary topic?**

*Write using full sentences and 1 or 2 paragraphs.*

## Major points

**Here you go over issues you identify in your reading of the paper. As a reviewer you don’t necessarily need to check all the results yourself, but you should point out concerns with, for example, assumptions or general appropriateness of methods. For example, you might comment on whether the statistical approach is adequate for answering the scientific questions. You can comment on how well they motivate the problem --- do they provide enough background for you to understand how this research fits into the big picture? Are there substantial analyses you feel are missing?**

*Write using a numbered list or bullet points, but full sentences. Make sure to indicate where each comment if referring to, if relevant.*

1. Referring to the second paragraph on page 1, this is the first major comment.

2. Referring to section 3 of the paper, this is the second major comment.

3. This is the third major comment.

4. Use this format for the rest of the comments.

## Minor points 

**Use this section to outline problems with clarity of writing, figures/tables, etc. Is the report well-formatted? Do the figures have labels and legends? Is the writing clear?**


*Write using a numbered list or bullet points, but full sentences. Make sure to indicate where each comment if referring to, if relevant.*

1. In the last paragraph of page 4, this is the first minor point.

2. In figure 2, this is the second minor point.

3. In table 1, this is the third minor point.

4. Use this format for the rest of the minor points.

## Grammar

*It is not your responsibility to check the report for grammar, but if you see grammar issues as you are reading, list them here.*

1. On page 3, paragraph 5, you...

2. Use this format for the rest of the grammar points.

