---
title: "Homework 2"
subtitle: "BIOST 311"
author: "Nina Galanter"
date: \today
output: 
  pdf_document:
    toc: false
header-includes:
  - \usepackage{color}
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(formatR)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = "hide")
```


## Instructions

This assignment should be submitted on Canvas as a .pdf by 11:59pm on Thursday, April 13th. You are welcome to work together on the homework; however, final solutions should be written up individually. 

Unedited software output in the body of your assignment is not acceptable. Please round numerical values to 2--3 significant digits, and include your R code (if applicable) in the same document. See the "How to Write a Proper Homework" document on Canvas for additional guidelines.  

Each homework assignment is worth 20 points total. Problems are graded for correctness, according to the number of points given in the problem statement. Homeworks will be marked complete if you get at least 16/20 points, otherwise the homework is incomplete pending a possible revision. 

## 1. Simple linear regression with binary predictor

For this question, you will study the association between alcohol consumption in the past 2 weeks and systolic blood pressure using the `mri` dataset. The dataset and documentation can be found in the homework 2 page and in the week 2 module.

**Note: remember to include units**

a. Create a new binary variable indicating whether each participant consumed alcohol in the 2 weeks previous to their systolic blood pressure measurement (taken at the same time as the MRI). Provide relevant descriptive statistics for this new variable. (1 point)

b. We are interested in studying the association between alcohol consumption and systolic blood pressure. Make a graphical figure comparing the distribution of systolic blood pressure among those who did and did not consume alcohol in the 2 weeks prior to the visit. Describe the plots. (1 point)

c. Write a statistical question that will allow us to examine the association between alcohol consumption and systolic blood pressure through linear regression. What is our population of interest? What is our parameter? (2 points)

d. Perform a linear regression analysis to answer the statistical question from part (b). Be sure to include a statistic with appropriate uncertainty quantification, as well as a hypothesis test. Be sure to state the null and alternative hypotheses. You should interpret your results; don't just give numerical output. (2 points) 

e. Since alcohol consumption is a binary variable, we could also approach this problem without using linear regression. Perform and interpret a t-test (assume equal variances) comparing the average systolic blood in those with and without alcohol consumption in the 2 weeks prior to the visit. Be sure to state the null and alternative hypotheses. (2 points)

f. What do you notice about your results from parts (d) and (e)? Do they agree? (1 point)

\newpage

## 2. Simple linear regression with quantitative predictor

In this problem, you will study this association between systolic blood pressure at the MRI visit and atrophy score using statistical inference. 

**Note: remember to include units**

a. Write a statistical question that will allow us to examine the association between systolic blood pressure at the MRI visit and atrophy score using linear regression. What is the parameter of interest? (2 points)

b. Perform a linear regression analysis to answer the statistical question from part (a). Be sure to include a statistic with appropriate uncertainty quantification, as well as a hypothesis test. Be sure to state the null and alternative hypotheses. You should interpret your results; don't just give numerical output. (2 points)  

c. What is the interpretation of the intercept of the model you fit in part (b)? Does this intercept make scientific sense? (1 point)

d. Produce a scatterplot of systolic blood pressure vs. atrophy score. Include your regression line from part (b) on the graph. (If you get stuck, try Google!) (2 points)

e. The four traditional linear regression assumptions are linearity, independence, Normality of errors, and equal variance. For each of these assumptions, assess whether or not you think the assumption is violated. If appropriate, use graphs to support your argument. (3 points)

f. Based on the results of part (e), do you have major concerns about your linear regression analysis and its appropriateness for answering the scientific question? Write a few sentences explaining your rationale. (1 point)